### ISSUE TITLE
Large number of errors in php error_log file

### ISSUE THREAD

**Issue by Wegerich** [joshuadavidnelson/scripts-to-footer#13]
[08-Jan-2020 15:06:24 UTC] Scripts-to-Footer Plugin Error: Error in post type check check
    [08-Jan-2020 15:35:16 UTC] Scripts-to-Footer Plugin Error: Error in taxonomy check

I'm getting hundreds of these two errors every month, which is making it harder to find other errors. Is there anything that can be done to fix it?

I'm running my install in `site.com/wp`, I don't know if that's what the taxonomy check means.

**Comment by joshuadavidnelson** [comment]
Hey there! It looks like there are conditions where custom post types and taxonomies exist, but the check is false/null and it's dumping out that "error" in the log. The plugin is working fine, I need to pull out the error notice, it should not be outputting that.

I'll get an update out over the weekend to address this.

**Comment by Wegerich** [comment]
Thank you very much, looking forward to it. Let me know if it would be helpful for you to have more details about the cause

**Comment by Wegerich** [comment]
I just realised that the start of these logs coincides with a bug on the site where 3700 discount coupons were created in woocommerce until the host locked out the server due to overload. 

Is it possible that this scripts-to-footer bug was related to this, either a cause or an effect?

**Comment by joshuadavidnelson** [comment]
It's possible the errors in the logs are caused by one of the post types created by WooCommerce, if the entries in the debug log to start when you activated both plugins, but it could be your log was deleted before that, or you updated to a more current version of the plugin with the log entry code in it - lots of possible reasons.

That said, STF doesn't really interact with creation of posts/coupons/etc, so I don't see any real way Scripts to Footer cause that behavoir in WooCommerce.

**Comment by Wegerich** [comment]
Thanks Joshua. Any idea when you might have time to work on the fix for this?

**Comment by joshuadavidnelson** [comment]
Yes! Actually, I had some time last night to make these updates, I have [PR open now](https://github.com/joshuadavidnelson/scripts-to-footer/pull/14). I'm going to run a few final checks later today/tonight and get a release out in the next day or so.

You can use the [`develop` branch](https://github.com/joshuadavidnelson/scripts-to-footer/tree/develop) version for now, or turn off [`WP_DEBUG`](https://wordpress.org/support/article/debugging-in-wordpress/) and they will go away entirely.

**Comment by Wegerich** [comment]
Thanks, I have installed the develop branch onto the site. I will let you know if I run into any problems.
