### ISSUE TITLE
Combine this plugin with minqueue

### ISSUE THREAD

**Issue by madvik** [joshuadavidnelson/scripts-to-footer#6]
I want to use this script but I use [minqueue](https://wordpress.org/plugins/minqueue/).
When `scripts-to-footer` is activate, the concatenation don't work. 

Thanks

**Comment by joshuadavidnelson** [comment]
@madvik I'm swamped with client work for the next couple of weeks, but I'm hoping to circle back to this and a few other open-source projects. I'll look at minqueue and get back to you (looks like that plugin hasn't been actively updated in 3 years). Let me know if that timeline doesn't work.

**Comment by madvik** [comment]
Thanks,
Minqueue has not been update since 3 years, but the plugins works fine, no bug, no problem and simple. For me, it the most attractive "combined resoussource" plugins.

**Comment by joshuadavidnelson** [comment]
Ok, sounds good. The developer is still active and works at a good agency, so it's probably not a big concern that it's 3-years-old. I'll circle back in a few weeks with an update.

**Comment by joshuadavidnelson** [comment]
Just a follow up, I haven't had a chance to get around to this, but I'm hoping to get an update on this plugin soon, hopefully including some compatibility for this issue.

**Comment by joshuadavidnelson** [comment]
It appears minqueue is not being supported, 7 years without an update and no replies on recent support forum posts. I won't be adding support to the core of Scripts to Footer for this plugin. If you're still looking for a solution, drop me a line on my site or email and I'd be happy to provide a quote for custom work.
