### ISSUE TITLE
This plugin isn't moving my scripts to the footer.

### ISSUE THREAD

**Issue by SeAlgoAsoma** [joshuadavidnelson/scripts-to-footer#7]
'Nuff said. It's just not happening. I do see jQuery in the footer now, but I also see it, and a bunch of other theme scripts, up in the <head>. I checked the theme, it's properly using enqueue for the scripts.

**Comment by joshuadavidnelson** [comment]
@SeAlgoAsoma That's very odd, happy to help diagnose and fix the issue. Can you provide me with some more information? A url with the plugin active? Can you confirm the scripts in the head are enqueued correctly by the theme/plugin(s). Does it occur site-wide or only on specific pages?

**Comment by joshuadavidnelson** [comment]
I'm closing this issue, no response in over a year.
